Add sposify

diff --git a/.github/workflows/Build and Release.yml b/.github/workflows/Build and Release.yml
--- a/.github/workflows/Build and Release.yml
+++ b/.github/workflows/Build and Release.yml
@@ -9,6 +9,11 @@ on:
       CHANGEVERSION:
         description: "SpotveeC Version Number"
         required: false
+      USESPOSIFY:
+        description: "Also inject the Sposify tweak"
+        required: true
+        default: true
+        type: boolean
       USEACTIONSEEVEE:
         description: "Get EeveeSpotify from latest EeveeSpotfiy build action"
         required: true
@@ -192,6 +197,181 @@ jobs:
         if: ${{ env.VT_ENABLED == 'true' }}
         run: echo "VTORION=${{ steps.vt-orion.outputs.analysis }}" >> $GITHUB_ENV
 
+      - name: Download and process Sposify
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' }}
+        run: |
+          # Download the Packages file
+          curl -sSL https://repo.dynastic.co/Packages -o Packages
+
+          # Use awk to find entries for com.spos, Architecture: iphoneos-arm, find the highest version
+          # extract the version, filename, SHA256 Hash, and MD5 hash
+          SPOSIFYVERSION=$(awk 'BEGIN { RS = ""; FS = "\n"; highest_version = "" } $1 ~ /^Package: com.spos$/ && $0 ~ /Architecture: iphoneos-arm([^6]|$)/ { for (i = 1; i <= NF; i++) { if ($i ~ /^Version: /) { split($i, a, " "); version = a[2]; if (highest_version == "" || version > highest_version) { highest_version = version } } } } END { if (highest_version != "") print highest_version }' Packages)
+          echo "Sposify Version Extracted: $SPOSIFYVERSION"
+          FILENAME=$(awk 'BEGIN{RS="";FS="\n";highest_version=""} $1~/^Package: com.spos$/ && $0~/Architecture: iphoneos-arm/{current_version="";current_filename="";for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^Filename: /){split($i,a," ");current_filename=a[2]}}if(highest_version==""||current_version>highest_version){highest_version=current_version;highest_filename=current_filename}} END{if(highest_version!="")print highest_filename}' Packages)
+          echo "Sposify FileName Extracted: $FILENAME"
+          SHA256=$(awk 'BEGIN{RS="";FS="\n";highest_version="";sha256="noSHA"} $1~/^Package: com.spos$/ && $0~/Architecture: iphoneos-arm/{current_version="";sha256_found=0;for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^SHA256: /){split($i,a," ");sha256=a[2];sha256_found=1}}if(highest_version==""||current_version>highest_version){highest_version=current_version;if(sha256_found==1){highest_sha256=sha256}else{highest_sha256="noSHA"}}}END{if(highest_version!="")print highest_sha256}' Packages)
+          echo "Sposify SHA256 Hash Extracted: $SHA256"
+          MD5=$(awk 'BEGIN{RS="";FS="\n";highest_version="";md5sum="noMD5"} $1~/^Package: com.spos$/ && $0~/Architecture: iphoneos-arm/{current_version="";for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^MD5Sum: /){split($i,a," ");md5sum=a[2]}}if(highest_version==""||current_version>highest_version){highest_version=current_version;highest_md5sum=md5sum}} END{if(highest_version!="")print highest_md5sum}' Packages)
+          echo "Sposify MD5 Hash Extracted: $MD5"
+
+          echo "Downloading From: https://repo.dynastic.co/$FILENAME"
+          # Download the file using curl
+          curl -LJO "https://repo.dynastic.co/$FILENAME"
+          downloaded_file=$(ls -t | head -n1)
+          mv "$downloaded_file" "Build Components/"
+          sposify="Build Components/$downloaded_file"
+          echo "Sposify path: $sposify"
+
+          #Check Hash
+          if [[ "${SHA256}" != "noSHA" ]]; then
+            echo "Expected SHA256 Hash: ${SHA256}"
+            calculated_sha256=$(shasum -a 256 "$sposify" | awk '{print $1}')
+            echo "Calculated SHA256 Hash: $calculated_sha256"
+            if [[ "${calculated_sha256}" == "${SHA256}" ]]; then
+              echo "SHA256 matches. Continuing..."
+            else
+              echo "SHA256 does not match."
+              exit 1
+            fi
+          elif [[ "${MD5}" != "noMD5" ]]; then
+            echo "Expected MD5 Hash: ${MD5}"
+            calculated_md5=$(md5 -q "$sposify" | awk '{print $1}')
+            echo "Calculated MD5 Hash: $calculated_md5"
+            if [[ "${calculated_md5}" == "${MD5}" ]]; then
+              echo "MD5 matches. Continuing..."
+            else
+              echo "MD5 does not match."
+              exit 1
+            fi
+          else
+            echo "Neither SHA256 nor MD5 is valid"
+            exit 1
+          fi
+
+          #CleanUp
+          rm -f Packages
+
+          #Set Env Varibles
+          echo "sposify=Build Components/$downloaded_file" >> $GITHUB_ENV
+          echo "SPOSIFYVERSION=$SPOSIFYVERSION" >> $GITHUB_ENV
+
+      - name: Upload Sposify to VirusTotal
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' && env.VT_ENABLED == 'true' }}
+        uses: crazy-max/ghaction-virustotal@v4
+        id: vt-sposify
+        with:
+          files: "${{ env.sposify }}"
+          vt_api_key: ${{ secrets.VIRUSTOTALKEY }}
+
+      - name: Set VirusTotal Analysis URL for Sposify
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' && env.VT_ENABLED == 'true' }}
+        run: echo "VTSPOSIFY=${{ steps.vt-sposify.outputs.analysis }}" >> $GITHUB_ENV
+
+      - name: Download and process SposifyFix
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' }}
+        run: |
+          # Download the Packages file
+          curl -sSL https://level3tjg.me/repo/Packages -o Packages
+
+          # Use awk to find entries for dev.theos.orion14, Architecture: iphoneos-arm, find the highest version
+          # extract the version, filename, SHA256 Hash, and MD5 hash
+          SPOSIFYFIXVERSION=$(awk 'BEGIN { RS = ""; FS = "\n"; highest_version = "" } $1 ~ /^Package: com.level3tjg.sposifyfix$/ && $0 ~ /Architecture: iphoneos-arm([^6]|$)/ { for (i = 1; i <= NF; i++) { if ($i ~ /^Version: /) { split($i, a, " "); version = a[2]; if (highest_version == "" || version > highest_version) { highest_version = version } } } } END { if (highest_version != "") print highest_version }' Packages)
+          echo "SposifyFix Version Extracted: $SPOSIFYFIXVERSION"
+          FILENAME=$(awk 'BEGIN{RS="";FS="\n";highest_version=""} $1~/^Package: com.level3tjg.sposifyfix$/ && $0~/Architecture: iphoneos-arm/{current_version="";current_filename="";for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^Filename: /){split($i,a," ");current_filename=a[2]}}if(highest_version==""||current_version>highest_version){highest_version=current_version;highest_filename=current_filename}} END{if(highest_version!="")print highest_filename}' Packages)
+          echo "SposifyFix FileName Extracted: $FILENAME"
+          SHA256=$(awk 'BEGIN{RS="";FS="\n";highest_version="";sha256="noSHA"} $1~/^Package: com.level3tjg.sposifyfix$/ && $0~/Architecture: iphoneos-arm/{current_version="";sha256_found=0;for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^SHA256: /){split($i,a," ");sha256=a[2];sha256_found=1}}if(highest_version==""||current_version>highest_version){highest_version=current_version;if(sha256_found==1){highest_sha256=sha256}else{highest_sha256="noSHA"}}}END{if(highest_version!="")print highest_sha256}' Packages)
+          echo "SposifyFix SHA256 Hash Extracted: $SHA256"
+          MD5=$(awk 'BEGIN{RS="";FS="\n";highest_version="";md5sum="noMD5"} $1~/^Package: ccom.level3tjg.sposifyfix$/ && $0~/Architecture: iphoneos-arm/{current_version="";for(i=1;i<=NF;i++){if($i~/^Version: /){split($i,a," ");version=a[2];if(current_version==""||version>current_version){current_version=version}}else if($i~/^MD5Sum: /){split($i,a," ");md5sum=a[2]}}if(highest_version==""||current_version>highest_version){highest_version=current_version;highest_md5sum=md5sum}} END{if(highest_version!="")print highest_md5sum}' Packages)
+          echo "SposifyFix MD5 Hash Extracted: $MD5"
+
+          echo "Downloading From: https://level3tjg.me/repo/Packages/$FILENAME"
+          # Download the file using curl
+          curl -LJO "https://level3tjg.me/repo/$FILENAME"
+          downloaded_file=$(ls -t | head -n1)
+          mv "$downloaded_file" "Build Components/"
+          sposifyfix="Build Components/$downloaded_file"
+          echo "SposifyFix path: $sposifyfix"
+
+          #Check Hash
+          if [[ "${SHA256}" != "noSHA" ]]; then
+            echo "Expected SHA256 Hash: ${SHA256}"
+            calculated_sha256=$(shasum -a 256 "$sposifyfix" | awk '{print $1}')
+            echo "Calculated SHA256 Hash: $calculated_sha256"
+            if [[ "${calculated_sha256}" == "${SHA256}" ]]; then
+              echo "SHA256 matches. Continuing..."
+            else
+              echo "SHA256 does not match."
+              exit 1
+            fi
+          elif [[ "${MD5}" != "noMD5" ]]; then
+            echo "Expected MD5 Hash: ${MD5}"
+            calculated_md5=$(md5 -q "$sposifyfix" | awk '{print $1}')
+            echo "Calculated MD5 Hash: $calculated_md5"
+            if [[ "${calculated_md5}" == "${MD5}" ]]; then
+              echo "MD5 matches. Continuing..."
+            else
+              echo "MD5 does not match."
+              exit 1
+            fi
+          else
+            echo "Neither SHA256 nor MD5 is valid"
+            exit 1
+          fi
+
+          #CleanUp
+          rm -f Packages
+
+          #Set Env Varibles
+          echo "sposifyfix=Build Components/$downloaded_file" >> $GITHUB_ENV
+          echo "SPOSIFYFIXVERSION=$SPOSIFYFIXVERSION" >> $GITHUB_ENV
+
+      - name: Upload SposifyFix to VirusTotal
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' && env.VT_ENABLED == 'true' }}
+        uses: crazy-max/ghaction-virustotal@v4
+        id: vt-sposifyfix
+        with:
+          files: "${{ env.sposifyfix }}"
+          vt_api_key: ${{ secrets.VIRUSTOTALKEY }}
+
+      - name: Set VirusTotal Analysis URL for SposifyFix
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' && env.VT_ENABLED == 'true' }}
+        run: echo "VTSPOSIFYFIX=${{ steps.vt-sposifyfix.outputs.analysis }}" >> $GITHUB_ENV
+
+      - name: Clone OpenSpotifySafariExtension
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' }}
+        run: git clone https://github.com/whoeevee/OpenSpotifySafariExtension
+
+      - name: Copy OpenSpotifySafariExtension.appex to Build Components
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' }}
+        run: |
+          cp -R OpenSpotifySafariExtension/OpenSpotifySafariExtension.appex "Build Components/OpenSpotifySafariExtension.appex"
+          echo "EXTCOMMIT=$(git -C OpenSpotifySafariExtension rev-parse --short HEAD)"
+          echo "EXTCOMMIT=$(git -C OpenSpotifySafariExtension rev-parse --short HEAD)" >> $GITHUB_ENV
+          echo "Extensions Commit is: ${{ env.EXTCOMMIT }}"
+          echo "OSSEXT=Build Components/OpenSpotifySafariExtension.appex" >> $GITHUB_ENV
+
+      - name: Compress OpenSpotifySafariExtension to zip
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' }}
+        run: |
+          cd OpenSpotifySafariExtension
+          echo "Compressing:"
+          ls
+          ditto -c -k --sequesterRsrc --keepParent ./ "../Build Components/OpenSpotifySafariExtension.zip"
+
+      - name: Upload OpenSpotifySafariExtension to VirusTotal
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' && env.VT_ENABLED == 'true' }}
+        uses: crazy-max/ghaction-virustotal@v4
+        id: vt-openspotify
+        with:
+          files: "Build Components/OpenSpotifySafariExtension.zip"
+          vt_api_key: ${{ secrets.VIRUSTOTALKEY }}
+
+      - name: Set VirusTotal Analysis URL for OpenSpotifySafariExtension
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' && env.VT_ENABLED == 'true' }}
+        run: |
+          echo "VTEXT=${{ steps.vt-openspotify.outputs.analysis }}" >> $GITHUB_ENV
+          rm -f "Build Components/OpenSpotifySafariExtension.zip"
+
       - name: Download EeveeSpotify .deb file from releases
         if: ${{ github.event.inputs.USEACTIONSEEVEE == 'false' }}
         run: |
@@ -291,6 +471,7 @@ jobs:
           rm -f Info.plist
 
       - name: Check if components were updated
+        # TODO handle sposify
         run: |
           latest_info=$(curl -s https://raw.githubusercontent.com/SpotCompiled/SpotC-Repo/refs/heads/main/AltStore%20Repo.json | jq '.apps[] | select(.name == "SpotveeC") | .information')
 
@@ -360,7 +541,12 @@ jobs:
 
       - name: Run Cyan
         run: |
-          Cyan -i "${{ env.spotifypath }}" -o "${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}.ipa" -v ${{ env.CHANGEVERSION }} -f "${{ env.orion }}" "${{ env.swiftprotobuf }}" "${{ env.eevee-arm64 }}" -u -w
+          if [ "${{ github.event.inputs.USESPOSIFY }}" = "true" ]; then
+            Cyan -i "${{ env.spotifypath }}" -o "${{ env.componentspath }}/SpotC++.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}.ipa" -v ${{ env.CHANGEVERSION }} -f "${{ env.sposifyfix }}" "${{ env.sposify }}" "${{ env.OSSEXT }}" "${{ env.orion }}" "${{ env.swiftprotobuf }}" "${{ env.eevee-arm }}" -u -w
+          else
+            Cyan -i "${{ env.spotifypath }}" -o "${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}.ipa" -v ${{ env.CHANGEVERSION }} -f "${{ env.orion }}" "${{ env.swiftprotobuf }}" "${{ env.eevee-arm64 }}" -u -w
+          fi
+
           echo "patchedspotify=${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}.ipa"
           echo "patchedspotify=${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}.ipa" >> $GITHUB_ENV
           echo "Patched Spotify .ipa Located: ${{ env.patchedspotify }}"
@@ -379,7 +565,12 @@ jobs:
 
       - name: Run AltStore Cyan
         run: |
-          Cyan -i "${{ env.spotifypath }}" -o "${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}_ALTSTORESOURCE_ONLY.ipa" -v ${{ env.CHANGEVERSION }} -b com.yodaluca23.SpotveeC -f "${{ env.orion }}" "${{ env.swiftprotobuf }}" "${{ env.eevee-arm64 }}" -u -w
+          if [ "${{ github.event.inputs.USESPOSIFY }}" = "true" ]; then
+            Cyan -i "${{ env.spotifypath }}" -o "${{ env.componentspath }}/SpotC++.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}_ALTSTORESOURCE_ONLY.ipa" -v ${{ env.CHANGEVERSION }} -b com.yodaluca23.SpotCPlusPlus -f "${{ env.sposifyfix }}" "${{ env.sposify }}" "${{ env.OSSEXT }}" "${{ env.orion }}" "${{ env.swiftprotobuf }}" "${{ env.eevee-arm }}" -u -w
+          else
+            Cyan -i "${{ env.spotifypath }}" -o "${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}_ALTSTORESOURCE_ONLY.ipa" -v ${{ env.CHANGEVERSION }} -b com.yodaluca23.SpotveeC -f "${{ env.orion }}" "${{ env.swiftprotobuf }}" "${{ env.eevee-arm64 }}" -u -w
+          fi
+
           echo "altpatchedspotify=${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}_ALTSTORESOURCE_ONLY.ipa"
           echo "altpatchedspotify=${{ env.componentspath }}/SpotveeC.v${{ env.CHANGEVERSION }}_v${{ env.VANILLASPOTIFYVERSION }}_ALTSTORESOURCE_ONLY.ipa" >> $GITHUB_ENV
           echo "AltStore Patched Spotify .ipa Located: ${{ env.altpatchedspotify }}"
@@ -440,6 +631,19 @@ jobs:
           echo "SwiftProtobuf VT: $VTSWIFTPROTOBUF"
           echo "VTSWIFTPROTOBUF=$VTSWIFTPROTOBUF" >> $GITHUB_ENV
 
+      - name: Extract and Prepare VirusTotal Links 2
+        if: ${{ github.event.inputs.USESPOSIFY == 'true' && env.VT_ENABLED == 'true' }}
+        run: |
+          VTSPOSIFY=$(echo "$VTSPOSIFY" | sed 's/.*\(https:\/\/.*\)/\1/')
+          echo "Sposify VT: $VTSPOSIFY"
+          echo "VTSPOSIFY=$VTSPOSIFY" >> $GITHUB_ENV
+          VTSPOSIFYFIX=$(echo "$VTSPOSIFYFIX" | sed 's/.*\(https:\/\/.*\)/\1/')
+          echo "SposifyFix VT: $VTSPOSIFYFIX"
+          echo "VTSPOSIFYFIX=$VTSPOSIFYFIX" >> $GITHUB_ENV
+          VTEXT=$(echo "$VTEXT" | sed 's/.*\(https:\/\/.*\)/\1/')
+          echo "OpenSpotifySafariExtension VT: $VTEXT"
+          echo "VTEXT=$VTEXT" >> $GITHUB_ENV
+
       - name: Construct ChangeLog Pt.1
         run: |
           echo "## ChangeLog" > changelog.txt
@@ -455,6 +659,7 @@ jobs:
           echo "$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ env.EEVEEREPO }}/commits?since=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ env.EEVEEREPO }}/releases/latest | jq -r .published_at)" | jq -r '.[].commit.message' | grep -Ev "update: repo|Merge branch .+ of .+ into .+" | sed 's/^/- (EeveeSpotify) /')" >> changelog.txt
 
       - name: Contruct ChangeLog Pt.3 (Add updated component lines)
+        # TODO handle sposify
         run: |
           if [ "${{ env.SPOTIFY_UPDATED }}" = 'true' ]; then
             echo "- Updated Spotify to version ${{ env.VANILLASPOTIFYVERSION }} </br>" >> changelog.txt
@@ -511,6 +716,14 @@ jobs:
           echo "<br><a href='${{ env.VTSPOTV }}'>SpotveeC VirusTotal</a></p>" >> changelog.txt
           echo "<p>AltStore SpotveeC Version: v${{ env.CHANGEVERSION }}" >> changelog.txt
           echo "<br><a href='${{ env.VTALTSPOTV }}'>AltStore SpotveeC VirusTotal</a></p>" >> changelog.txt
+          if [ "${{ github.event.inputs.USESPOSIFY }}" = "true" ]; then
+            echo "<p>Sposify v${{ env.SPOSIFYVERSION }}" >> changelog.txt
+            echo "<br><a href='${{ env.VTSPOSIFY }}'>Sposify VirusTotal</a></p>" >> changelog.txt
+            echo "<p>OpenSpotifySafariExtension Commit: ${{ env.EXTCOMMIT }}" >> changelog.txt
+            echo "<br><a href='${{ env.VTEXT }}'>OpenSpotifySafariExtension Repo Compressed .zip VirusTotal</a></p>" >> changelog.txt
+            echo "<p>Sposify Fix v${{ env.SPOSIFYFIXVERSION }}" >> changelog.txt
+            echo "<br><a href='${{ env.VTSPOSIFYFIX }}'>Sposify Fix VirusTotal</a></p>" >> changelog.txt
+          fi
           echo "</details>" >> changelog.txt
 
       - name: Construct ChangeLog Pt.8 (Add file name dropdown)
@@ -589,6 +802,7 @@ jobs:
           echo "ALTSTORECHANGELOG=$ALTSTORECHANGELOG" >> $GITHUB_ENV
 
       - name: Update AltStore Repo.json
+        # TODO handle sposify
         if: ${{ github.event.inputs.UPLOADTOSTORES == 'true' }}
         run: |
           ENTITLE=$(cat "./Build Components/Entitlements.json")
@@ -664,6 +878,7 @@ jobs:
         run: curl "https://raw.githubusercontent.com/SpotCompiled/SpotC-Repo/main/Scarlet%20Repo.json" -o ./ScarletRepo.json
 
       - name: Update Scarlet Repo.json
+        # TODO handle sposify
         if: ${{ github.event.inputs.UPLOADTOSTORES == 'true' }}
         run: |
           jq --arg CHANGEVERSION "${{ env.CHANGEVERSION }}" \
